[phases.setup]
nixPkgs = ["python39", "python39Packages.pip"]

[phases.build]
commands = ["pip install -r requirements.txt"]

[phases.start]
commands = ["uvicorn main:app --host 0.0.0.0 --port 8000"]
